spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080


aws:
  s3-bucket: bucket
  localstack:
    hostname: http://localhost:4566