spring:

  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      auto-offset-reset: earliest
      group-id: consumer
      topic: "pdf"

server:
  port: 8081

aws:
  s3-bucket: bucket
  localstack:
    hostname: http://localhost:4566