spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOSTNAME}
      port: 27017
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      database: cv

  kafka:
    producer:
      bootstrap-servers: ${SPRING_KAFKA_PRODUCER_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

aws:
  s3-bucket: bucket
  localstack:
    hostname: http://localhost:4566