spring:

  data:
    mongodb:
      host: mongo_db
      port: 27017
      database: cv
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      topic: "pdf"

server:
  port: 8080

aws:
  s3-bucket: bucket
  localstack:
    hostname: http://localhost:4566
